version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=fishKekse
    ports:
      - '3306:3306'
    volumes:
      - "./db_init/setup.sql:/docker-entrypoint-initdb.d/1.sql"